export default function * () {
  yield { 
    title: "Autogenerated page number 4",
    content: "content of page 4"
  };
  yield { 
    title: "Autogenerated page number 5",
    content: "content of page 5"
  };
  yield { 
    title: "Autogenerated page number 6",
    content: "content of page 6",
    url: "./custom-permalink"
  };
}