name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: v1.x

      - name: Testing
        run: |
          git clone https://github.com/lumeland/lume.git
          deno test --unstable --allow-read
          deno run --unstable -A lume/cli.js run multi
          deno run --unstable -A lume/cli.js build
